### ISSUE TITLE
跨平台实现简单的弹窗,思路？

### ISSUE THREAD

**Issue by jiagushuai** [waruqi/gbox#3]
我在Windows上使用MessageBox函数实现弹窗提示,
Mac上可以直接调用系统API,不用qt之类的第三方框架吗？
项目使用C++编写,对界面要求只是弹窗输入框这些。有什么实现思路吗？
因为看到这个图形库暂不支持使用,所以在Mac简单实现弹窗可以怎么样呢

**Comment by waruqi** [comment]
这个项目暂时处于停滞状态，不过后期可能还会重新启动的，你现在的问题暂时 无法做各种技术上的建议，你可以自己网上看下mac下的ui开发。

**Comment by jiagushuai** [comment]
嗯嗯 谢谢
