### ISSUE TITLE
s/gb_cavas_stroke_miter_set/gb_canvas_stroke_miter_set/

### ISSUE THREAD

**Issue by ntd** [waruqi/gbox#4]
This is not a PR because I was just surfing your project to see what this was about.

In [canvas.c](https://github.com/tboox/gbox/blob/master/src/gbox/core/canvas.c#L471) and [canvas.h](https://github.com/tboox/gbox/blob/master/src/gbox/core/canvas.h#L283) you have `cavas` instead of `canvas`.

**Comment by waruqi** [comment]
Thank you, this is a typo, but I don't plan to fix it at the moment, because I don't maintain this project anymore. But I am currently rewriting the entire project internally, and I will fix these problems. Maybe I will update it again in half a year.

**Comment by ntd** [comment]
No problem. Feel free to close this issue if you wish.
